name = "MITA-MingRenCup"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["MITA-MingRenCup"]

[[require]]
name = "Calculus@JokerXin"
path = "/Users/zhoukexin/desktop/Mitar/Universes/Calculus@JokerXin/"

[[lean_lib]]
name = "MITA-MingRenCup"
