name = "Lean2TeX"
version = "0.1.0"
defaultTargets = ["Lean2TeX"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[lean_lib]]
name = "Lean2TeX"
